export const flagArray = [
    'albania.png',
    'algeria.png',
    'andorra.png',
    'angola.png',
    'antigua and barbuda.png',
    'argentina.png',
    'armenia.png',
    'australia.png',
    'austria.png',
    'azerbaijan.png',
    'bahamas.png',
    'bahrain.png',
    'bangladesh.png',
    'barbados.png',
    'belarus.png',
    'belgium.png',
    'belize.png',
    'benin.png',
    'bhutan.png',
    'bolivia.png',
    'bosnia and herzegovina.png',
    'botswana.png',
    'brazil.png',
    'brunei.png',
    'bulgaria.png',
    'burkina faso.png',
    'burundi.png',
    'cambodia.png',
    'cameroon.png',
    'canada.png',
    'cape verde.png',
    'central african republic.png',
    'chad.png',
    'chile.png',
    'china.png',
    'colombia.png',
    'comoros.png',
    'costa rica.png',
    'croatia.png',
    'cuba.png',
    'cyprus.png',
    'czechia.png',
    'democratic republic of the congo.png',
    'denmark.png',
    'djibouti.png',
    'dominica.png',
    'dominican republic.png',
    'ecuador.png',
    'egypt.png',
    'el salvador.png',
    'equatorial guinea.png',
    'eritrea.png',
    'estonia.png',
    'eswatini.png',
    'ethiopia.png',
    'fiji.png',
    'finland.png',
    'france.png',
    'gabon.png',
    'gambia.png',
    'georgia.png',
    'germany.png',
    'ghana.png',
    'greece.png',
    'grenada.png',
    'guatemala.png',
    'guinea.png',
    'guinea-bissau.png',
    'guyana.png',
    'haiti.png',
    'honduras.png',
    'hungary.png',
    'iceland.png',
    'india.png',
    'indonesia.png',
    'iran.png',
    'iraq.png',
    'ireland.png',
    'israel.png',
    'italy.png',
    'ivory coast.png',
    'jamaica.png',
    'japan.png',
    'jordan.png',
    'kazakhstan.png',
    'kenya.png',
    'kiribati.png',
    'kuwait.png',
    'kyrgyzstan.png',
    'laos.png',
    'latvia.png',
    'lebanon.png',
    'lesotho.png',
    'liberia.png',
    //Need to find correct Libya flag
    'liechtenstein.png',
    'lithuania.png',
    'luxembourg.png',
    'madagascar.png',
    'malawi.png',
    'malaysia.png',
    'maldives.png',
    'mali.png',
    'malta.png',
    'marshall islands.png',
    //Need to find correct Mauritania flag
    'mauritius.png',
    'mexico.png',
    'micronesia.png',
    'moldova.png',
    'monaco.png',
    'mongolia.png',
    'montenegro.png',
    'morocco.png',
    'mozambique.png',
    'myanmar.png',
    'namibia.png',
    'nauru.png',
    'nepal.png',
    //Need to find better Nepal flag
    'netherlands.png',
    'new zealand.png',
    'nicaragua.png',
    'niger.png',
    'nigeria.png',
    'north korea.png',
    'north macedonia.png',
    //need to find better North Macedonia flag
    'norway.png',
    'oman.png',
    'pakistan.png',
    'palau.png',
    'palestine.png',
    'panama.png',
    'papua new guinea.png',
    'paraguay.png',
    'peru.png',
    'philippines.png',
    'poland.png',
    'portugal.png',
    'qatar.png',
    'romania.png',
    'russia.png',
    'rwanda.png',
    //Need to find better San Marino flag
    //Need to find better Slovina flag
    //Need to find better Solomon Islands flag
    'saint kitts and nevis.png',
    'saint lucia.png',
    'saint vincent and the grenadines.png',
    'samoa.png',
    'sao tome and principe.png',
    'saudi arabia.png',
    'senegal.png',
    'serbia.png',
    'seychelles.png',
    'sierra leone.png',
    'singapore.png',
    'slovakia.png',
    'slovenia.png',
    'solomon islands.png',
    'somalia.png',
    'south africa.png',
    'south korea.png',
    //Need to find South Sudan flag
    'spain.png',
    'sri lanka.png',
    'sudan.png',
    'suriname.png',
    'sweden.png',
    'switzerland.png',
    'syria.png',
    'taiwan.png',
    'tajikistan.png',
    'tanzania.png',
    'thailand.png',
    'timor-leste.png',
    'togo.png',
    'tonga.png',
    'trinidad and tobago.png',
    'tunisia.png',
    'turkey.png',
    'turkmenistan.png',
    'tuvalu.png',
    'uganda.png',
    'ukraine.png',
    'united arab emirates.png',
    'united kingdom.png',
    'united states of america.png',
    'uruguay.png',
    'uzbekistan.png',
    'vanuatu.png',
    'vatican city.png',
    'venezuela.png',
    'vietnam.png',
    'yemen.png',
    'zambia.png',
    'zimbabwe.png'
];