export const flagArray = [
    'albania.png',
    'algeria.png',
    'andorra.png',
    'angola.png',
    'antigua and barbuda.png',
    'argentina.png',
    'armenia.png',
    'australia.png',
    'austria.png',
    'azerbaijan.png',
    'bahamas.png',
    'bahrain.png',
    'bangladesh.png',
    'barbados.png',
    'belarus.png',
    'belgium.png',
    'belize.png',
    'benin.png',
    'bhutan.png',
    'bolivia.png',
    'bosnia and herzegovina.png',
    'botswana.png',
    'brazil.png',
    'brunei.png',
    'bulgaria.png',
    'burkina faso.png',
    'burundi.png',
    'cambodia.png',
    'cameroon.png',
    'canada.png',
    'cape verde.png',
    'central african republic.png',
    'chad.png',
    'chile.png',
    'china.png',
    'colombia.png',
    'comoros.png',
    'costa rica.png',
    'croatia.png',
    'cuba.png',
    'cyprus.png',
    'czechia.png',
    'democratic republic of the congo.png',
    'denmark.png',
    'djibouti.png',
    'dominica.png',
    'dominican republic.png',
    'ecuador.png',
    'egypt.png',
    'el salvador.png',
    'equatorial guinea.png',
    'eritrea.png',
    'estonia.png',
    'eswatini.png',
    'ethiopia.png',
    'fiji.png',
    'finland.png',
    'france.png',
    'gabon.png',
    'gambia.png',
    'georgia.png',
    'germany.png',
    'ghana.png',
    'greece.png',
    'grenada.png',
    'guatemala.png',
    'guinea.png',
    'guinea-bissau.png',
    'guyana.png',
    'haiti.png',
    'honduras.png',
    'hungary.png', //red looks like orange
    'iceland.png',
    'india.png',
    'indonesia.png',
    'iran.png',
    'iraq.png',
    'ireland.png',
    'israel.png',
    'italy.png',
    'ivory coast.png',
    'jamaica.png',
    'japan.png',
    'jordan.png',
    'kazakhstan.png',
    'kenya.png',
    'kiribati.png',
    'kuwait.png',
    'kyrgyzstan.png',
    'laos.png',
    'latvia.png',
    'lebanon.png',
    'lesotho.png',
    'liberia.png',
    //Need to find correct Libya flag
    'liechtenstein.png',
    'lithuania.png',
    'luxembourg.png',
    'mexico.png',
    'mozambique.png',
    'namibia.png',
    'netherlands.png',
    'north korea.png',
    'norway.png',
    'oman.png',
    'pakistan.png',
    'palau.png',
    'panama.png',
    'papua new guinea.png',
    'paraguay.png',
    'peru.png',
    'philippines.png',
    'poland.png',
    'portugal.png',
    'qatar.png',
    'romania.png',
    'russia.png',
    'rwanda.png',
    'seychelles.png',
    'south africa.png',
    'sweden.png',
    'tanzania.png',
    'tonga.png',
    'usa.png',
    'vanuatu.png',
    'vatican city.png'
];